package easydel.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 구 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AddressGu implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 구_이름. */
	private String guName;

	/** 동 테이블 목록. */
	private Set<AddressDong> addressDongsSet;

	/**
	 * 생성자.
	 */
	public AddressGu() {
		this.addressDongsSet = new HashSet<AddressDong>();
	}

	/**
	 * 구_이름을 설정합니다..
	 * 
	 * @param guName
	 *            구_이름
	 */
	public void setGuName(String guName) {
		this.guName = guName;
	}

	/**
	 * 구_이름을 가져옵니다..
	 * 
	 * @return 구_이름
	 */
	public String getGuName() {
		return this.guName;
	}

	/**
	 * 동 테이블 목록을 설정합니다..
	 * 
	 * @param addressDongsSet
	 *            동 테이블 목록
	 */
	public void setAddressDongsSet(Set<AddressDong> addressDongsSet) {
		this.addressDongsSet = addressDongsSet;
	}

	/**
	 * 동 테이블를 추가합니다..
	 * 
	 * @param addressDongs
	 *            동 테이블
	 */
	public void addAddressDongs(AddressDong addressDongs) {
		this.addressDongsSet.add(addressDongs);
	}

	/**
	 * 동 테이블 목록을 가져옵니다..
	 * 
	 * @return 동 테이블 목록
	 */
	public Set<AddressDong> getAddressDongsSet() {
		return this.addressDongsSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((guName == null) ? 0 : guName.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AddressGu other = (AddressGu) obj;
		if (guName == null) {
			if (other.guName != null) {
				return false;
			}
		} else if (!guName.equals(other.guName)) {
			return false;
		}
		return true;
	}

}
