package easydel.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 동 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AddressDong implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 동 코드. */
	private Integer dongId;

	/** 구 테이블. */
	private AddressGu guDescriptionaddressGus;

	/** 동_이름. */
	private String dongDesc;

	/** 동x좌표. */
	private Integer coordinateX;

	/** 동y좌표. */
	private Integer coordinateY;
	
	/** 의뢰건 목록. */
	private Set<Request> requestsSet;

	/**
	 * 생성자.
	 */
	public AddressDong() {
		this.requestsSet = new HashSet<Request>();
	}

	/**
	 * 동 코드을 설정합니다..
	 * 
	 * @param dongId
	 *            동 코드
	 */
	public void setDongId(Integer dongId) {
		this.dongId = dongId;
	}

	/**
	 * 동 코드을 가져옵니다..
	 * 
	 * @return 동 코드
	 */
	public Integer getDongId() {
		return this.dongId;
	}

	/**
	 * 구 테이블을 설정합니다..
	 * 
	 * @param guDescriptionaddressGus
	 *            구 테이블
	 */
	public void setGuDescriptionaddressGus(AddressGu guDescriptionaddressGus) {
		this.guDescriptionaddressGus = guDescriptionaddressGus;
	}

	/**
	 * 구 테이블을 가져옵니다..
	 * 
	 * @return 구 테이블
	 */
	public AddressGu getGuDescriptionaddressGus() {
		return this.guDescriptionaddressGus;
	}

	/**
	 * 동_이름을 설정합니다..
	 * 
	 * @param dongDesc
	 *            동_이름
	 */
	public void setDongDesc(String dongDesc) {
		this.dongDesc = dongDesc;
	}

	/**
	 * 동_이름을 가져옵니다..
	 * 
	 * @return 동_이름
	 */
	public String getDongDesc() {
		return this.dongDesc;
	}

	/**
	 * 동x좌표을 설정합니다..
	 * 
	 * @param coordinateX
	 *            동x좌표
	 */
	public void setCoordinateX(Integer coordinateX) {
		this.coordinateX = coordinateX;
	}

	/**
	 * 동x좌표을 가져옵니다..
	 * 
	 * @return 동x좌표
	 */
	public Integer getCoordinateX() {
		return this.coordinateX;
	}

	/**
	 * 동y좌표을 설정합니다..
	 * 
	 * @param coordinateY
	 *            동y좌표
	 */
	public void setCoordinateY(Integer coordinateY) {
		this.coordinateY = coordinateY;
	}

	/**
	 * 동y좌표을 가져옵니다..
	 * 
	 * @return 동y좌표
	 */
	public Integer getCoordinateY() {
		return this.coordinateY;
	}

	/**
	 * 의뢰건 목록을 설정합니다..
	 * 
	 * @param requestsSet
	 *            의뢰건 목록
	 */
	public void setRequestsSet(Set<Request> requestsSet) {
		this.requestsSet = requestsSet;
	}

	/**
	 * 의뢰건를 추가합니다..
	 * 
	 * @param requests
	 *            의뢰건
	 */
	public void addRequests(Request requests) {
		this.requestsSet.add(requests);
	}

	/**
	 * 의뢰건 목록을 가져옵니다..
	 * 
	 * @return 의뢰건 목록
	 */
	public Set<Request> getRequestsSet() {
		return this.requestsSet;
	}


	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((dongId == null) ? 0 : dongId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AddressDong other = (AddressDong) obj;
		if (dongId == null) {
			if (other.dongId != null) {
				return false;
			}
		} else if (!dongId.equals(other.dongId)) {
			return false;
		}
		return true;
	}

}
