package easydel.entity;

import java.io.Serializable;

/**
 * 알림 로그 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AlertLog implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 알람 id 번호. */
	private Integer alertId;

	/** 회원. */
	private String userId;

	/** alert_comment. */
	private String alertComment;

	/** alert_status. */
	private Integer alertStatus;

	/**
	 * 생성자.
	 */
	public AlertLog() {
	}

	/**
	 * 알람 id 번호을 설정합니다..
	 * 
	 * @param alertId
	 *            알람 id 번호
	 */
	public void setAlertId(Integer alertId) {
		this.alertId = alertId;
	}

	/**
	 * 알람 id 번호을 가져옵니다..
	 * 
	 * @return 알람 id 번호
	 */
	public Integer getAlertId() {
		return this.alertId;
	}


	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * alert_comment을 설정합니다..
	 * 
	 * @param alertComment
	 *            alert_comment
	 */
	public void setAlertComment(String alertComment) {
		this.alertComment = alertComment;
	}

	/**
	 * alert_comment을 가져옵니다..
	 * 
	 * @return alert_comment
	 */
	public String getAlertComment() {
		return this.alertComment;
	}

	/**
	 * alert_status을 설정합니다..
	 * 
	 * @param alertStatus
	 *            alert_status
	 */
	public void setAlertStatus(Integer alertStatus) {
		this.alertStatus = alertStatus;
	}

	/**
	 * alert_status을 가져옵니다..
	 * 
	 * @return alert_status
	 */
	public Integer getAlertStatus() {
		return this.alertStatus;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((alertId == null) ? 0 : alertId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AlertLog other = (AlertLog) obj;
		if (alertId == null) {
			if (other.alertId != null) {
				return false;
			}
		} else if (!alertId.equals(other.alertId)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "AlertLog [alertId=" + alertId + ", userId=" + userId
				+ ", alertComment=" + alertComment + ", alertStatus="
				+ alertStatus + "]";
	}

}
