package easydel.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 거래완료 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CompleteDelivery implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 의뢰건. */
	private Request requests;

	/** 의뢰완료시간. */
	private Date finishTime;

	/** 배송자 평가 상태. */
	private Integer courierEvalstatus;

	/** 발송자 평가 상태. */
	private Integer senderEvalstatus;

	/** 배달부평가 목록. */
	private Set<CourierEval> courierEvalsSet;

	/** 발송인평가 목록. */
	private Set<SenderEval> senderEvalsSet;

	/**
	 * 생성자.
	 */
	public CompleteDelivery() {
		this.courierEvalsSet = new HashSet<CourierEval>();
		this.senderEvalsSet = new HashSet<SenderEval>();
	}

	/**
	 * 의뢰건을 설정합니다..
	 * 
	 * @param requests
	 *            의뢰건
	 */
	public void setRequests(Request requests) {
		this.requests = requests;
	}

	/**
	 * 의뢰건을 가져옵니다..
	 * 
	 * @return 의뢰건
	 */
	public Request getRequests() {
		return this.requests;
	}

	/**
	 * 의뢰완료시간을 설정합니다..
	 * 
	 * @param finishTime
	 *            의뢰완료시간
	 */
	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}

	/**
	 * 의뢰완료시간을 가져옵니다..
	 * 
	 * @return 의뢰완료시간
	 */
	public Date getFinishTime() {
		return this.finishTime;
	}

	/**
	 * 배송자 평가 상태을 설정합니다..
	 * 
	 * @param courierEvalstatus
	 *            배송자 평가 상태
	 */
	public void setCourierEvalstatus(Integer courierEvalstatus) {
		this.courierEvalstatus = courierEvalstatus;
	}

	/**
	 * 배송자 평가 상태을 가져옵니다..
	 * 
	 * @return 배송자 평가 상태
	 */
	public Integer getCourierEvalstatus() {
		return this.courierEvalstatus;
	}

	/**
	 * 발송자 평가 상태을 설정합니다..
	 * 
	 * @param senderEvalstatus
	 *            발송자 평가 상태
	 */
	public void setSenderEvalstatus(Integer senderEvalstatus) {
		this.senderEvalstatus = senderEvalstatus;
	}

	/**
	 * 발송자 평가 상태을 가져옵니다..
	 * 
	 * @return 발송자 평가 상태
	 */
	public Integer getSenderEvalstatus() {
		return this.senderEvalstatus;
	}

	/**
	 * 배달부평가 목록을 설정합니다..
	 * 
	 * @param courierEvalsSet
	 *            배달부평가 목록
	 */
	public void setCourierEvalsSet(Set<CourierEval> courierEvalsSet) {
		this.courierEvalsSet = courierEvalsSet;
	}

	/**
	 * 배달부평가를 추가합니다..
	 * 
	 * @param courierEvals
	 *            배달부평가
	 */
	public void addCourierEvals(CourierEval courierEvals) {
		this.courierEvalsSet.add(courierEvals);
	}

	/**
	 * 배달부평가 목록을 가져옵니다..
	 * 
	 * @return 배달부평가 목록
	 */
	public Set<CourierEval> getCourierEvalsSet() {
		return this.courierEvalsSet;
	}

	/**
	 * 발송인평가 목록을 설정합니다..
	 * 
	 * @param senderEvalsSet
	 *            발송인평가 목록
	 */
	public void setSenderEvalsSet(Set<SenderEval> senderEvalsSet) {
		this.senderEvalsSet = senderEvalsSet;
	}

	/**
	 * 발송인평가를 추가합니다..
	 * 
	 * @param senderEvals
	 *            발송인평가
	 */
	public void addSenderEvals(SenderEval senderEvals) {
		this.senderEvalsSet.add(senderEvals);
	}

	/**
	 * 발송인평가 목록을 가져옵니다..
	 * 
	 * @return 발송인평가 목록
	 */
	public Set<SenderEval> getSenderEvalsSet() {
		return this.senderEvalsSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((requests == null) ? 0 : requests.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CompleteDelivery other = (CompleteDelivery) obj;
		if (requests == null) {
			if (other.requests != null) {
				return false;
			}
		} else if (!requests.equals(other.requests)) {
			return false;
		}
		return true;
	}

}
