package easydel.entity;

import java.io.Serializable;

/**
 * 배달부평가 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CourierEval implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 의뢰건. */
	private Request requests;

	/** 회원. */
	private User courierIdusers;

	/** 배달부평가. */
	private String courierCmt;

	/**
	 * 생성자.
	 */
	public CourierEval() {
	}

	/**
	 * 의뢰건을 설정합니다..
	 * 
	 * @param requests
	 *            의뢰건
	 */
	public void setRequests(Request requests) {
		this.requests = requests;
	}

	/**
	 * 의뢰건을 가져옵니다..
	 * 
	 * @return 의뢰건
	 */
	public Request getRequests() {
		return this.requests;
	}

	/**
	 * 회원을 설정합니다..
	 * 
	 * @param courierIdusers
	 *            회원
	 */
	public void setCourierIdusers(User courierIdusers) {
		this.courierIdusers = courierIdusers;
	}

	/**
	 * 회원을 가져옵니다..
	 * 
	 * @return 회원
	 */
	public User getCourierIdusers() {
		return this.courierIdusers;
	}

	/**
	 * 배달부평가을 설정합니다..
	 * 
	 * @param courierCmt
	 *            배달부평가
	 */
	public void setCourierCmt(String courierCmt) {
		this.courierCmt = courierCmt;
	}

	/**
	 * 배달부평가을 가져옵니다..
	 * 
	 * @return 배달부평가
	 */
	public String getCourierCmt() {
		return this.courierCmt;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((requests == null) ? 0 : requests.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CourierEval other = (CourierEval) obj;
		if (requests == null) {
			if (other.requests != null) {
				return false;
			}
		} else if (!requests.equals(other.requests)) {
			return false;
		}
		return true;
	}

}
