package easydel.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * EDmoney입출금기록 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EdmoneyLog implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ED머니 거래번호. */
	private Integer logId;

	/** 회원. */
	private User users;

	/** 거래액. */
	private Integer withdrawAmount;

	/** 거래일시. */
	private Date actionDate;

	/**
	 * 생성자.
	 */
	public EdmoneyLog() {
	}

	/**
	 * ED머니 거래번호을 설정합니다..
	 * 
	 * @param logId
	 *            ED머니 거래번호
	 */
	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	/**
	 * ED머니 거래번호을 가져옵니다..
	 * 
	 * @return ED머니 거래번호
	 */
	public Integer getLogId() {
		return this.logId;
	}

	/**
	 * 회원을 설정합니다..
	 * 
	 * @param users
	 *            회원
	 */
	public void setUsers(User users) {
		this.users = users;
	}

	/**
	 * 회원을 가져옵니다..
	 * 
	 * @return 회원
	 */
	public User getUsers() {
		return this.users;
	}

	/**
	 * 거래액을 설정합니다..
	 * 
	 * @param withdrawAmount
	 *            거래액
	 */
	public void setWithdrawAmount(Integer withdrawAmount) {
		this.withdrawAmount = withdrawAmount;
	}

	/**
	 * 거래액을 가져옵니다..
	 * 
	 * @return 거래액
	 */
	public Integer getWithdrawAmount() {
		return this.withdrawAmount;
	}

	/**
	 * 거래일시을 설정합니다..
	 * 
	 * @param actionDate
	 *            거래일시
	 */
	public void setActionDate(Date actionDate) {
		this.actionDate = actionDate;
	}

	/**
	 * 거래일시을 가져옵니다..
	 * 
	 * @return 거래일시
	 */
	public Date getActionDate() {
		return this.actionDate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((logId == null) ? 0 : logId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EdmoneyLog other = (EdmoneyLog) obj;
		if (logId == null) {
			if (other.logId != null) {
				return false;
			}
		} else if (!logId.equals(other.logId)) {
			return false;
		}
		return true;
	}

}
