package easydel.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 신고사유 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ReportType implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 신고사유코드. */
	private Integer reportType;

	/** 신고사유상세. */
	private String reportTypeDesc;

	/** 신고 상태 목록. */
	private Set<Report> reportsSet;

	/**
	 * 생성자.
	 */
	public ReportType() {
		this.reportsSet = new HashSet<Report>();
	}

	/**
	 * 신고사유코드을 설정합니다..
	 * 
	 * @param reportType
	 *            신고사유코드
	 */
	public void setReportType(Integer reportType) {
		this.reportType = reportType;
	}

	/**
	 * 신고사유코드을 가져옵니다..
	 * 
	 * @return 신고사유코드
	 */
	public Integer getReportType() {
		return this.reportType;
	}

	/**
	 * 신고사유상세을 설정합니다..
	 * 
	 * @param reportTypeDesc
	 *            신고사유상세
	 */
	public void setReportTypeDesc(String reportTypeDesc) {
		this.reportTypeDesc = reportTypeDesc;
	}

	/**
	 * 신고사유상세을 가져옵니다..
	 * 
	 * @return 신고사유상세
	 */
	public String getReportTypeDesc() {
		return this.reportTypeDesc;
	}

	/**
	 * 신고 상태 목록을 설정합니다..
	 * 
	 * @param reportsSet
	 *            신고 상태 목록
	 */
	public void setReportsSet(Set<Report> reportsSet) {
		this.reportsSet = reportsSet;
	}

	/**
	 * 신고 상태를 추가합니다..
	 * 
	 * @param reports
	 *            신고 상태
	 */
	public void addReports(Report reports) {
		this.reportsSet.add(reports);
	}

	/**
	 * 신고 상태 목록을 가져옵니다..
	 * 
	 * @return 신고 상태 목록
	 */
	public Set<Report> getReportsSet() {
		return this.reportsSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((reportType == null) ? 0 : reportType.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ReportType other = (ReportType) obj;
		if (reportType == null) {
			if (other.reportType != null) {
				return false;
			}
		} else if (!reportType.equals(other.reportType)) {
			return false;
		}
		return true;
	}

}
