package easydel.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 신고 상태 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Report implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 신고번호. */
	private Integer reportId;

	/** 신고사유. */
	private ReportType reportType;

	/** 신고사유상세. */
	private String reportCmt;

	/** 의뢰건 목록. */
	private Set<Request> requestsSet;

	/**
	 * 생성자.
	 */
	public Report() {
		this.requestsSet = new HashSet<Request>();
	}

	/**
	 * 신고번호을 설정합니다..
	 * 
	 * @param reportId
	 *            신고번호
	 */
	public void setReportId(Integer reportId) {
		this.reportId = reportId;
	}

	/**
	 * 신고번호을 가져옵니다..
	 * 
	 * @return 신고번호
	 */
	public Integer getReportId() {
		return this.reportId;
	}

	/**
	 * 신고사유을 설정합니다..
	 * 
	 * @param reportType
	 *            신고사유
	 */
	public void setReportType(ReportType reportType) {
		this.reportType = reportType;
	}

	/**
	 * 신고사유을 가져옵니다..
	 * 
	 * @return 신고사유
	 */
	public ReportType getReportType() {
		return this.reportType;
	}

	/**
	 * 신고사유상세을 설정합니다..
	 * 
	 * @param reportCmt
	 *            신고사유상세
	 */
	public void setReportCmt(String reportCmt) {
		this.reportCmt = reportCmt;
	}

	/**
	 * 신고사유상세을 가져옵니다..
	 * 
	 * @return 신고사유상세
	 */
	public String getReportCmt() {
		return this.reportCmt;
	}

	/**
	 * 의뢰건 목록을 설정합니다..
	 * 
	 * @param requestsSet
	 *            의뢰건 목록
	 */
	public void setRequestsSet(Set<Request> requestsSet) {
		this.requestsSet = requestsSet;
	}

	/**
	 * 의뢰건를 추가합니다..
	 * 
	 * @param requests
	 *            의뢰건
	 */
	public void addRequests(Request requests) {
		this.requestsSet.add(requests);
	}

	/**
	 * 의뢰건 목록을 가져옵니다..
	 * 
	 * @return 의뢰건 목록
	 */
	public Set<Request> getRequestsSet() {
		return this.requestsSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((reportId == null) ? 0 : reportId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Report other = (Report) obj;
		if (reportId == null) {
			if (other.reportId != null) {
				return false;
			}
		} else if (!reportId.equals(other.reportId)) {
			return false;
		}
		return true;
	}

}
