package easydel.entity;

import java.io.Serializable;
import java.sql.Date;

/**
 * 신고 상태 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Report implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 의뢰건. */
	private Integer requestId;

	/** 신고사유. */
	private Integer reportType;

	/** 회원. */
	private String reportedUserId;
	
	private String reportUserId;

	/** 신고사유상세. */
	private String reportCmt;

	/** 신고 처리 상태. */
	private String reportStatus;
	
	private Date reportDate;

	/**
	 * 생성자.
	 */
	public Report() {
	}

	public Integer getRequestId() {
		return requestId;
	}

	public void setRequestId(Integer requestId) {
		this.requestId = requestId;
	}

	public Integer getReportType() {
		return reportType;
	}

	public void setReportType(Integer reportType) {
		this.reportType = reportType;
	}

	public String getReportedUserId() {
		return reportedUserId;
	}

	public void setReportedUserId(String reportedUserId) {
		this.reportedUserId = reportedUserId;
	}

	public String getReportCmt() {
		return reportCmt;
	}

	public void setReportCmt(String reportCmt) {
		this.reportCmt = reportCmt;
	}

	public String getReportStatus() {
		return reportStatus;
	}

	public void setReportStatus(String reportStatus) {
		this.reportStatus = reportStatus;
	}

	public String getReportUserId() {
		return reportUserId;
	}

	public void setReportUserId(String reportUserId) {
		this.reportUserId = reportUserId;
	}

	public Date getReportDate() {
		return reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	@Override
	public String toString() {
		return "Report [requestId=" + requestId + ", reportType=" + reportType
				+ ", reportedUserId=" + reportedUserId + ", reportUserId="
				+ reportUserId + ", reportCmt=" + reportCmt + ", reportStatus="
				+ reportStatus + ", reportDate=" + reportDate + "]";
	}
}
