package easydel.entity;

import java.io.Serializable;

/**
 * 운송글_코멘트 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RequestCmt implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 코멘트_번호. */
	private Integer cmtId;

	/** 의뢰건. */
	private Integer requestId;

	/** 회원. */
	private String userId;
	private String saveUserPictureByJoinWithUsers;

	/** 코멘트내용. */
	private String replyText;

	/** 코멘트_첨부사진. */
	private String replyPicture;

	/**
	 * 생성자.
	 */
	public RequestCmt() {
	}

	/**
	 * 코멘트_번호을 설정합니다..
	 * 
	 * @param cmtId
	 *            코멘트_번호
	 */
	public void setCmtId(Integer cmtId) {
		this.cmtId = cmtId;
	}

	/**
	 * 코멘트_번호을 가져옵니다..
	 * 
	 * @return 코멘트_번호
	 */
	public Integer getCmtId() {
		return this.cmtId;
	}
	
	public Integer getRequestId() {
		return requestId;
	}

	public void setRequestId(Integer requestId) {
		this.requestId = requestId;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * 코멘트내용을 설정합니다..
	 * 
	 * @param replyText
	 *            코멘트내용
	 */
	public void setReplyText(String replyText) {
		this.replyText = replyText;
	}

	/**
	 * 코멘트내용을 가져옵니다..
	 * 
	 * @return 코멘트내용
	 */
	public String getReplyText() {
		return this.replyText;
	}

	/**
	 * 코멘트_첨부사진을 설정합니다..
	 * 
	 * @param replyPicture
	 *            코멘트_첨부사진
	 */
	public void setReplyPicture(String replyPicture) {
		this.replyPicture = replyPicture;
	}

	/**
	 * 코멘트_첨부사진을 가져옵니다..
	 * 
	 * @return 코멘트_첨부사진
	 */
	public String getReplyPicture() {
		return this.replyPicture;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cmtId == null) ? 0 : cmtId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RequestCmt other = (RequestCmt) obj;
		if (cmtId == null) {
			if (other.cmtId != null) {
				return false;
			}
		} else if (!cmtId.equals(other.cmtId)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "RequestCmt [cmtId=" + cmtId + ", requestId=" + requestId
				+ ", userId=" + userId + ", saveUserPictureByJoinWithUsers="
				+ saveUserPictureByJoinWithUsers + ", replyText=" + replyText
				+ ", replyPicture=" + replyPicture + "]";
	}

	public String getSaveUserPictureByJoinWithUsers() {
		return saveUserPictureByJoinWithUsers;
	}

	public void setSaveUserPictureByJoinWithUsers(
			String saveUserPictureByJoinWithUsers) {
		this.saveUserPictureByJoinWithUsers = saveUserPictureByJoinWithUsers;
	}

}
