package easydel.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 의뢰건 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Request implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 의뢰_번호. */
	private Integer requestId;

	/** 회원. */
	private String senderId;

	/** 회원. */
	private String courierId;

	/** 의뢰 종류. */
	private String requestType;

	/** 글 상태. */
	private Integer requestStatus;

	/** 배달물_이름. */
	private String cargoName;

	/** 운임. */
	private Integer deliveryPrice;

	/** 배달물_사진. */
	private String cargoPicture;

	/** 배달물_상세. */
	private String cargoDesc;

	/** 보내는 사람 연락처. */
	private String senderPhone;

	/** 전달시간(최소). */
	private Date pickupMinTime;

	/** 전달시간(최대). */
	private Date pickupMaxTime;

	/** 동 테이블. */
	private Integer pickupPlace;

	/** 전달_상세 장소. */
	private String pickupPlaceDesc;

	/** 수취인 이름. */
	private String receiverName;

	/** 수취인 연락처. */
	private String receiverPhone;

	/** 배달시간(최소). */
	private Date arrivalMinTime;

	/** 배달시간(최대). */
	private Date arrivalMaxTime;

	/** 동 테이블. */
	private Integer arrivalPlace;

	/** 배달장소_상세. */
	private String arrivalPlaceDesc;

	/** 부재시 메세지. */
	private String absenceMessage;

	/** 인증번호. */
	private Integer validationCode;

	/** 신고 상태. */
	private Integer reportStatus;

	/** 글 소멸 시각. */
	private Date expireDate;

	/** 거래완료 목록. */
	private Set<CompleteDelivery> completeDeliverysSet;

	/** 운송글_코멘트 목록. */
	private Set<RequestCmt> requestCmtsSet;

	/**
	 * 생성자.
	 */
	public Request() {
		this.completeDeliverysSet = new HashSet<CompleteDelivery>();
		this.requestCmtsSet = new HashSet<RequestCmt>();
	}
	
	public Integer getReportStatus() {
		return reportStatus;
	}

	public void setReportStatus(Integer reportStatus) {
		this.reportStatus = reportStatus;
	}

	/**
	 * 의뢰_번호을 설정합니다..
	 * 
	 * @param requestId
	 *            의뢰_번호
	 */
	public void setRequestId(Integer requestId) {
		this.requestId = requestId;
	}

	/**
	 * 의뢰_번호을 가져옵니다..
	 * 
	 * @return 의뢰_번호
	 */
	public Integer getRequestId() {
		return this.requestId;
	}

	/**
	 * 의뢰 종류을 설정합니다..
	 * 
	 * @param requestType
	 *            의뢰 종류
	 */
	public void setRequestType(String requestType) {
		this.requestType = requestType;
	}

	/**
	 * 의뢰 종류을 가져옵니다..
	 * 
	 * @return 의뢰 종류
	 */
	public String getRequestType() {
		return this.requestType;
	}

	/**
	 * 글 상태을 설정합니다..
	 * 
	 * @param requestStatus
	 *            글 상태
	 */
	public void setRequestStatus(Integer requestStatus) {
		this.requestStatus = requestStatus;
	}

	/**
	 * 글 상태을 가져옵니다..
	 * 
	 * @return 글 상태
	 */
	public Integer getRequestStatus() {
		return this.requestStatus;
	}

	/**
	 * 배달물_이름을 설정합니다..
	 * 
	 * @param cargoName
	 *            배달물_이름
	 */
	public void setCargoName(String cargoName) {
		this.cargoName = cargoName;
	}

	/**
	 * 배달물_이름을 가져옵니다..
	 * 
	 * @return 배달물_이름
	 */
	public String getCargoName() {
		return this.cargoName;
	}

	/**
	 * 운임을 설정합니다..
	 * 
	 * @param deliveryPrice
	 *            운임
	 */
	public void setDeliveryPrice(Integer deliveryPrice) {
		this.deliveryPrice = deliveryPrice;
	}

	/**
	 * 운임을 가져옵니다..
	 * 
	 * @return 운임
	 */
	public Integer getDeliveryPrice() {
		return this.deliveryPrice;
	}

	/**
	 * 배달물_사진을 설정합니다..
	 * 
	 * @param cargoPicture
	 *            배달물_사진
	 */
	public void setCargoPicture(String cargoPicture) {
		this.cargoPicture = cargoPicture;
	}

	/**
	 * 배달물_사진을 가져옵니다..
	 * 
	 * @return 배달물_사진
	 */
	public String getCargoPicture() {
		return this.cargoPicture;
	}

	/**
	 * 배달물_상세을 설정합니다..
	 * 
	 * @param cargoDesc
	 *            배달물_상세
	 */
	public void setCargoDesc(String cargoDesc) {
		this.cargoDesc = cargoDesc;
	}

	/**
	 * 배달물_상세을 가져옵니다..
	 * 
	 * @return 배달물_상세
	 */
	public String getCargoDesc() {
		return this.cargoDesc;
	}

	/**
	 * 보내는 사람 연락처을 설정합니다..
	 * 
	 * @param senderPhone
	 *            보내는 사람 연락처
	 */
	public void setSenderPhone(String senderPhone) {
		this.senderPhone = senderPhone;
	}

	/**
	 * 보내는 사람 연락처을 가져옵니다..
	 * 
	 * @return 보내는 사람 연락처
	 */
	public String getSenderPhone() {
		return this.senderPhone;
	}

	/**
	 * 전달시간(최소)을 설정합니다..
	 * 
	 * @param pickupMinTime
	 *            전달시간(최소)
	 */
	public void setPickupMinTime(Date pickupMinTime) {
		this.pickupMinTime = pickupMinTime;
	}

	/**
	 * 전달시간(최소)을 가져옵니다..
	 * 
	 * @return 전달시간(최소)
	 */
	public Date getPickupMinTime() {
		return this.pickupMinTime;
	}

	/**
	 * 전달시간(최대)을 설정합니다..
	 * 
	 * @param pickupMaxTime
	 *            전달시간(최대)
	 */
	public void setPickupMaxTime(Date pickupMaxTime) {
		this.pickupMaxTime = pickupMaxTime;
	}

	/**
	 * 전달시간(최대)을 가져옵니다..
	 * 
	 * @return 전달시간(최대)
	 */
	public Date getPickupMaxTime() {
		return this.pickupMaxTime;
	}


	/**
	 * 전달_상세 장소을 설정합니다..
	 * 
	 * @param pickupPlaceDesc
	 *            전달_상세 장소
	 */
	public void setPickupPlaceDesc(String pickupPlaceDesc) {
		this.pickupPlaceDesc = pickupPlaceDesc;
	}

	/**
	 * 전달_상세 장소을 가져옵니다..
	 * 
	 * @return 전달_상세 장소
	 */
	public String getPickupPlaceDesc() {
		return this.pickupPlaceDesc;
	}

	/**
	 * 수취인 이름을 설정합니다..
	 * 
	 * @param receiverName
	 *            수취인 이름
	 */
	public void setReceiverName(String receiverName) {
		this.receiverName = receiverName;
	}

	/**
	 * 수취인 이름을 가져옵니다..
	 * 
	 * @return 수취인 이름
	 */
	public String getReceiverName() {
		return this.receiverName;
	}

	/**
	 * 수취인 연락처을 설정합니다..
	 * 
	 * @param receiverPhone
	 *            수취인 연락처
	 */
	public void setReceiverPhone(String receiverPhone) {
		this.receiverPhone = receiverPhone;
	}

	/**
	 * 수취인 연락처을 가져옵니다..
	 * 
	 * @return 수취인 연락처
	 */
	public String getReceiverPhone() {
		return this.receiverPhone;
	}

	/**
	 * 배달시간(최소)을 설정합니다..
	 * 
	 * @param arrivalMinTime
	 *            배달시간(최소)
	 */
	public void setArrivalMinTime(Date arrivalMinTime) {
		this.arrivalMinTime = arrivalMinTime;
	}

	/**
	 * 배달시간(최소)을 가져옵니다..
	 * 
	 * @return 배달시간(최소)
	 */
	public Date getArrivalMinTime() {
		return this.arrivalMinTime;
	}

	/**
	 * 배달시간(최대)을 설정합니다..
	 * 
	 * @param arrivalMaxTime
	 *            배달시간(최대)
	 */
	public void setArrivalMaxTime(Date arrivalMaxTime) {
		this.arrivalMaxTime = arrivalMaxTime;
	}

	/**
	 * 배달시간(최대)을 가져옵니다..
	 * 
	 * @return 배달시간(최대)
	 */
	public Date getArrivalMaxTime() {
		return this.arrivalMaxTime;
	}

	/**
	 * 배달장소_상세을 설정합니다..
	 * 
	 * @param arrivalPlaceDesc
	 *            배달장소_상세
	 */
	public void setArrivalPlaceDesc(String arrivalPlaceDesc) {
		this.arrivalPlaceDesc = arrivalPlaceDesc;
	}

	/**
	 * 배달장소_상세을 가져옵니다..
	 * 
	 * @return 배달장소_상세
	 */
	public String getArrivalPlaceDesc() {
		return this.arrivalPlaceDesc;
	}

	/**
	 * 부재시 메세지을 설정합니다..
	 * 
	 * @param absenceMessage
	 *            부재시 메세지
	 */
	public void setAbsenceMessage(String absenceMessage) {
		this.absenceMessage = absenceMessage;
	}

	/**
	 * 부재시 메세지을 가져옵니다..
	 * 
	 * @return 부재시 메세지
	 */
	public String getAbsenceMessage() {
		return this.absenceMessage;
	}

	/**
	 * 인증번호을 설정합니다..
	 * 
	 * @param validationCode
	 *            인증번호
	 */
	public void setValidationCode(Integer validationCode) {
		this.validationCode = validationCode;
	}

	/**
	 * 인증번호을 가져옵니다..
	 * 
	 * @return 인증번호
	 */
	public Integer getValidationCode() {
		return this.validationCode;
	}

	/**
	 * 글 소멸 시각을 설정합니다..
	 * 
	 * @param expireDate
	 *            글 소멸 시각
	 */
	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

	/**
	 * 글 소멸 시각을 가져옵니다..
	 * 
	 * @return 글 소멸 시각
	 */
	public Date getExpireDate() {
		return this.expireDate;
	}

	/**
	 * 거래완료 목록을 설정합니다..
	 * 
	 * @param completeDeliverysSet
	 *            거래완료 목록
	 */
	public void setCompleteDeliverysSet(Set<CompleteDelivery> completeDeliverysSet) {
		this.completeDeliverysSet = completeDeliverysSet;
	}

	/**
	 * 거래완료를 추가합니다..
	 * 
	 * @param completeDeliverys
	 *            거래완료
	 */
	public void addCompleteDeliverys(CompleteDelivery completeDeliverys) {
		this.completeDeliverysSet.add(completeDeliverys);
	}
	
	public String getSenderId() {
		return senderId;
	}

	public void setSenderId(String senderId) {
		this.senderId = senderId;
	}

	public String getCourierId() {
		return courierId;
	}

	public void setCourierId(String courierId) {
		this.courierId = courierId;
	}

	public Integer getPickupPlace() {
		return pickupPlace;
	}

	public void setPickupPlace(Integer pickupPlace) {
		this.pickupPlace = pickupPlace;
	}

	public Integer getArrivalPlace() {
		return arrivalPlace;
	}

	public void setArrivalPlace(Integer arrivalPlace) {
		this.arrivalPlace = arrivalPlace;
	}

	/**
	 * 거래완료 목록을 가져옵니다..
	 * 
	 * @return 거래완료 목록
	 */
	public Set<CompleteDelivery> getCompleteDeliverysSet() {
		return this.completeDeliverysSet;
	}

	/**
	 * 운송글_코멘트 목록을 설정합니다..
	 * 
	 * @param requestCmtsSet
	 *            운송글_코멘트 목록
	 */
	public void setRequestCmtsSet(Set<RequestCmt> requestCmtsSet) {
		this.requestCmtsSet = requestCmtsSet;
	}

	/**
	 * 운송글_코멘트를 추가합니다..
	 * 
	 * @param requestCmts
	 *            운송글_코멘트
	 */
	public void addRequestCmts(RequestCmt requestCmts) {
		this.requestCmtsSet.add(requestCmts);
	}

	/**
	 * 운송글_코멘트 목록을 가져옵니다..
	 * 
	 * @return 운송글_코멘트 목록
	 */
	public Set<RequestCmt> getRequestCmtsSet() {
		return this.requestCmtsSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((requestId == null) ? 0 : requestId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Request other = (Request) obj;
		if (requestId == null) {
			if (other.requestId != null) {
				return false;
			}
		} else if (!requestId.equals(other.requestId)) {
			return false;
		}
		return true;
	}

}
