package easydel.entity;

import java.io.Serializable;

/**
 * 발송인평가 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SenderEval implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 의뢰건. */
	private Request requests;

	/** 회원. */
	private User senderIdusers;

	/** 발송 코멘트. */
	private String senderCmt;

	/**
	 * 생성자.
	 */
	public SenderEval() {
	}

	/**
	 * 의뢰건을 설정합니다..
	 * 
	 * @param requests
	 *            의뢰건
	 */
	public void setRequests(Request requests) {
		this.requests = requests;
	}

	/**
	 * 의뢰건을 가져옵니다..
	 * 
	 * @return 의뢰건
	 */
	public Request getRequests() {
		return this.requests;
	}

	/**
	 * 회원을 설정합니다..
	 * 
	 * @param senderIdusers
	 *            회원
	 */
	public void setSenderIdusers(User senderIdusers) {
		this.senderIdusers = senderIdusers;
	}

	/**
	 * 회원을 가져옵니다..
	 * 
	 * @return 회원
	 */
	public User getSenderIdusers() {
		return this.senderIdusers;
	}

	/**
	 * 발송 코멘트을 설정합니다..
	 * 
	 * @param senderCmt
	 *            발송 코멘트
	 */
	public void setSenderCmt(String senderCmt) {
		this.senderCmt = senderCmt;
	}

	/**
	 * 발송 코멘트을 가져옵니다..
	 * 
	 * @return 발송 코멘트
	 */
	public String getSenderCmt() {
		return this.senderCmt;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((requests == null) ? 0 : requests.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SenderEval other = (SenderEval) obj;
		if (requests == null) {
			if (other.requests != null) {
				return false;
			}
		} else if (!requests.equals(other.requests)) {
			return false;
		}
		return true;
	}

}
