package easydel.entity;

import java.io.Serializable;
import java.sql.Date;

/**
 * 발송인평가 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SenderEval implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 의뢰건. */
	private Integer requestId;

	/** 회원. */
	private String senderId;

	/** 발송 코멘트. */
	private String senderCmt;
	
	private Date regDate;
	private Integer senderTime;
	private Integer senderKind;
	private Integer senderThing;
	
	public SenderEval() {
		super();
	}
	public Integer getRequestId() {
		return requestId;
	}
	public void setRequestId(Integer requestId) {
		this.requestId = requestId;
	}
	public String getSenderId() {
		return senderId;
	}
	public void setSenderId(String senderId) {
		this.senderId = senderId;
	}
	public String getSenderCmt() {
		return senderCmt;
	}
	public void setSenderCmt(String senderCmt) {
		this.senderCmt = senderCmt;
	}
	public Date getRegDate() {
		return regDate;
	}
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}
	public Integer getSenderTime() {
		return senderTime;
	}
	public void setSenderTime(Integer senderTime) {
		this.senderTime = senderTime;
	}
	public Integer getSenderKind() {
		return senderKind;
	}
	public void setSenderKind(Integer senderKind) {
		this.senderKind = senderKind;
	}
	public Integer getSenderThing() {
		return senderThing;
	}
	public void setSenderThing(Integer senderThing) {
		this.senderThing = senderThing;
	}
	@Override
	public String toString() {
		return "SenderEval [requestId=" + requestId + ", senderId=" + senderId
				+ ", senderCmt=" + senderCmt + ", regDate=" + regDate
				+ ", senderTime=" + senderTime + ", senderKind=" + senderKind
				+ ", senderThing=" + senderThing + "]";
	}
}
