package easydel.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 회원 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class User implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 회원ID. */
	private String userId;

	/** 회원명. */
	private String userName;

	/** 회원PW. */
	private String userPassword;

	/** 회원 회원성별. */
	private Integer userGender;

	/** 회원email. */
	private String userEmail;

	/** 회원생년월일. */
	private Date userBirthdate;

	/** 회원전화번호. */
	private String userPhone;

	/** 회원사진. */
	private String userPicture;

	/** ED머니 잔고. */
	private Integer edmoneyBalance;

	/** 배달평점_시간정확. */
	private Integer courierAvgTime;

	/** 배달평점_친절도. */
	private Integer courierAvgKind;

	/** 배달평점_안전성. */
	private Integer courierAvgSafe;

	/** 운송거래건수. */
	private Integer courierTotalcnt;

	/** 운송거래 성사건수. */
	private Integer courierSuccesscnt;

	/** 발송평점_시간정확. */
	private Integer senderAvgTime;

	/** 발송평점_친절도. */
	private Integer senderAvgKind;

	/** 발송평점_물건정확성. */
	private Integer senderAvgThing;

	/** 배송거래건수. */
	private Integer senderTotalcnt;

	/** 배송거래 성사건수. */
	private Integer senderSuccesscnt;

	/** 알림 로그 목록. */
	private Set<AlertLog> alertLogsSet;

	/** 운송글_코멘트 목록. */
	private Set<RequestCmt> requestCmtsSet;

	/** 배달부평가 목록. */
	private Set<CourierEval> courierEvalsSet;

	/** 발송인평가 목록. */
	private Set<SenderEval> senderEvalsSet;

	/** EDmoney입출금기록 목록. */
	private Set<EdmoneyLog> edmoneyLogsSet;

	/** 의뢰건 목록. */
	private Set<Request> requestsSet;

	/**
	 * 생성자.
	 */
	public User() {
		this.courierEvalsSet = new HashSet<CourierEval>();
		this.requestsSet = new HashSet<Request>();
		this.senderEvalsSet = new HashSet<SenderEval>();
		this.alertLogsSet = new HashSet<AlertLog>();
		this.edmoneyLogsSet = new HashSet<EdmoneyLog>();
		this.requestCmtsSet = new HashSet<RequestCmt>();
	}

	/**
	 * 회원ID을 설정합니다..
	 * 
	 * @param userId
	 *            회원ID
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * 회원ID을 가져옵니다..
	 * 
	 * @return 회원ID
	 */
	public String getUserId() {
		return this.userId;
	}

	/**
	 * 회원명을 설정합니다..
	 * 
	 * @param userName
	 *            회원명
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * 회원명을 가져옵니다..
	 * 
	 * @return 회원명
	 */
	public String getUserName() {
		return this.userName;
	}

	/**
	 * 회원PW을 설정합니다..
	 * 
	 * @param userPassword
	 *            회원PW
	 */
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	/**
	 * 회원PW을 가져옵니다..
	 * 
	 * @return 회원PW
	 */
	public String getUserPassword() {
		return this.userPassword;
	}

	/**
	 * 회원 회원성별을 설정합니다..
	 * 
	 * @param userGender
	 *            회원 회원성별
	 */
	public void setUserGender(Integer userGender) {
		this.userGender = userGender;
	}

	/**
	 * 회원 회원성별을 가져옵니다..
	 * 
	 * @return 회원 회원성별
	 */
	public Integer getUserGender() {
		return this.userGender;
	}

	/**
	 * 회원email을 설정합니다..
	 * 
	 * @param userEmail
	 *            회원email
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	/**
	 * 회원email을 가져옵니다..
	 * 
	 * @return 회원email
	 */
	public String getUserEmail() {
		return this.userEmail;
	}

	/**
	 * 회원생년월일을 설정합니다..
	 * 
	 * @param userBirthdate
	 *            회원생년월일
	 */
	public void setUserBirthdate(Date userBirthdate) {
		this.userBirthdate = userBirthdate;
	}

	/**
	 * 회원생년월일을 가져옵니다..
	 * 
	 * @return 회원생년월일
	 */
	public Date getUserBirthdate() {
		return this.userBirthdate;
	}

	/**
	 * 회원전화번호을 설정합니다..
	 * 
	 * @param userPhone
	 *            회원전화번호
	 */
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	/**
	 * 회원전화번호을 가져옵니다..
	 * 
	 * @return 회원전화번호
	 */
	public String getUserPhone() {
		return this.userPhone;
	}

	/**
	 * 회원사진을 설정합니다..
	 * 
	 * @param userPicture
	 *            회원사진
	 */
	public void setUserPicture(String userPicture) {
		this.userPicture = userPicture;
	}

	/**
	 * 회원사진을 가져옵니다..
	 * 
	 * @return 회원사진
	 */
	public String getUserPicture() {
		return this.userPicture;
	}

	/**
	 * ED머니 잔고을 설정합니다..
	 * 
	 * @param edmoneyBalance
	 *            ED머니 잔고
	 */
	public void setEdmoneyBalance(Integer edmoneyBalance) {
		this.edmoneyBalance = edmoneyBalance;
	}

	/**
	 * ED머니 잔고을 가져옵니다..
	 * 
	 * @return ED머니 잔고
	 */
	public Integer getEdmoneyBalance() {
		return this.edmoneyBalance;
	}

	/**
	 * 배달평점_시간정확을 설정합니다..
	 * 
	 * @param courierAvgTime
	 *            배달평점_시간정확
	 */
	public void setCourierAvgTime(Integer courierAvgTime) {
		this.courierAvgTime = courierAvgTime;
	}

	/**
	 * 배달평점_시간정확을 가져옵니다..
	 * 
	 * @return 배달평점_시간정확
	 */
	public Integer getCourierAvgTime() {
		return this.courierAvgTime;
	}

	/**
	 * 배달평점_친절도을 설정합니다..
	 * 
	 * @param courierAvgKind
	 *            배달평점_친절도
	 */
	public void setCourierAvgKind(Integer courierAvgKind) {
		this.courierAvgKind = courierAvgKind;
	}

	/**
	 * 배달평점_친절도을 가져옵니다..
	 * 
	 * @return 배달평점_친절도
	 */
	public Integer getCourierAvgKind() {
		return this.courierAvgKind;
	}

	/**
	 * 배달평점_안전성을 설정합니다..
	 * 
	 * @param courierAvgSafe
	 *            배달평점_안전성
	 */
	public void setCourierAvgSafe(Integer courierAvgSafe) {
		this.courierAvgSafe = courierAvgSafe;
	}

	/**
	 * 배달평점_안전성을 가져옵니다..
	 * 
	 * @return 배달평점_안전성
	 */
	public Integer getCourierAvgSafe() {
		return this.courierAvgSafe;
	}

	/**
	 * 운송거래건수을 설정합니다..
	 * 
	 * @param courierTotalcnt
	 *            운송거래건수
	 */
	public void setCourierTotalcnt(Integer courierTotalcnt) {
		this.courierTotalcnt = courierTotalcnt;
	}

	/**
	 * 운송거래건수을 가져옵니다..
	 * 
	 * @return 운송거래건수
	 */
	public Integer getCourierTotalcnt() {
		return this.courierTotalcnt;
	}

	/**
	 * 운송거래 성사건수을 설정합니다..
	 * 
	 * @param courierSuccesscnt
	 *            운송거래 성사건수
	 */
	public void setCourierSuccesscnt(Integer courierSuccesscnt) {
		this.courierSuccesscnt = courierSuccesscnt;
	}

	/**
	 * 운송거래 성사건수을 가져옵니다..
	 * 
	 * @return 운송거래 성사건수
	 */
	public Integer getCourierSuccesscnt() {
		return this.courierSuccesscnt;
	}

	/**
	 * 발송평점_시간정확을 설정합니다..
	 * 
	 * @param senderAvgTime
	 *            발송평점_시간정확
	 */
	public void setSenderAvgTime(Integer senderAvgTime) {
		this.senderAvgTime = senderAvgTime;
	}

	/**
	 * 발송평점_시간정확을 가져옵니다..
	 * 
	 * @return 발송평점_시간정확
	 */
	public Integer getSenderAvgTime() {
		return this.senderAvgTime;
	}

	/**
	 * 발송평점_친절도을 설정합니다..
	 * 
	 * @param senderAvgKind
	 *            발송평점_친절도
	 */
	public void setSenderAvgKind(Integer senderAvgKind) {
		this.senderAvgKind = senderAvgKind;
	}

	/**
	 * 발송평점_친절도을 가져옵니다..
	 * 
	 * @return 발송평점_친절도
	 */
	public Integer getSenderAvgKind() {
		return this.senderAvgKind;
	}

	/**
	 * 발송평점_물건정확성을 설정합니다..
	 * 
	 * @param senderAvgThing
	 *            발송평점_물건정확성
	 */
	public void setSenderAvgThing(Integer senderAvgThing) {
		this.senderAvgThing = senderAvgThing;
	}

	/**
	 * 발송평점_물건정확성을 가져옵니다..
	 * 
	 * @return 발송평점_물건정확성
	 */
	public Integer getSenderAvgThing() {
		return this.senderAvgThing;
	}

	/**
	 * 배송거래건수을 설정합니다..
	 * 
	 * @param senderTotalcnt
	 *            배송거래건수
	 */
	public void setSenderTotalcnt(Integer senderTotalcnt) {
		this.senderTotalcnt = senderTotalcnt;
	}

	/**
	 * 배송거래건수을 가져옵니다..
	 * 
	 * @return 배송거래건수
	 */
	public Integer getSenderTotalcnt() {
		return this.senderTotalcnt;
	}

	/**
	 * 배송거래 성사건수을 설정합니다..
	 * 
	 * @param senderSuccesscnt
	 *            배송거래 성사건수
	 */
	public void setSenderSuccesscnt(Integer senderSuccesscnt) {
		this.senderSuccesscnt = senderSuccesscnt;
	}

	/**
	 * 배송거래 성사건수을 가져옵니다..
	 * 
	 * @return 배송거래 성사건수
	 */
	public Integer getSenderSuccesscnt() {
		return this.senderSuccesscnt;
	}

	/**
	 * 알림 로그 목록을 설정합니다..
	 * 
	 * @param alertLogsSet
	 *            알림 로그 목록
	 */
	public void setAlertLogsSet(Set<AlertLog> alertLogsSet) {
		this.alertLogsSet = alertLogsSet;
	}

	/**
	 * 알림 로그를 추가합니다..
	 * 
	 * @param alertLogs
	 *            알림 로그
	 */
	public void addAlertLogs(AlertLog alertLogs) {
		this.alertLogsSet.add(alertLogs);
	}

	/**
	 * 알림 로그 목록을 가져옵니다..
	 * 
	 * @return 알림 로그 목록
	 */
	public Set<AlertLog> getAlertLogsSet() {
		return this.alertLogsSet;
	}

	/**
	 * 운송글_코멘트 목록을 설정합니다..
	 * 
	 * @param requestCmtsSet
	 *            운송글_코멘트 목록
	 */
	public void setRequestCmtsSet(Set<RequestCmt> requestCmtsSet) {
		this.requestCmtsSet = requestCmtsSet;
	}

	/**
	 * 운송글_코멘트를 추가합니다..
	 * 
	 * @param requestCmts
	 *            운송글_코멘트
	 */
	public void addRequestCmts(RequestCmt requestCmts) {
		this.requestCmtsSet.add(requestCmts);
	}

	/**
	 * 운송글_코멘트 목록을 가져옵니다..
	 * 
	 * @return 운송글_코멘트 목록
	 */
	public Set<RequestCmt> getRequestCmtsSet() {
		return this.requestCmtsSet;
	}

	/**
	 * 배달부평가 목록을 설정합니다..
	 * 
	 * @param courierEvalsSet
	 *            배달부평가 목록
	 */
	public void setCourierEvalsSet(Set<CourierEval> courierEvalsSet) {
		this.courierEvalsSet = courierEvalsSet;
	}

	/**
	 * 배달부평가를 추가합니다..
	 * 
	 * @param courierEvals
	 *            배달부평가
	 */
	public void addCourierEvals(CourierEval courierEvals) {
		this.courierEvalsSet.add(courierEvals);
	}

	/**
	 * 배달부평가 목록을 가져옵니다..
	 * 
	 * @return 배달부평가 목록
	 */
	public Set<CourierEval> getCourierEvalsSet() {
		return this.courierEvalsSet;
	}

	/**
	 * 발송인평가 목록을 설정합니다..
	 * 
	 * @param senderEvalsSet
	 *            발송인평가 목록
	 */
	public void setSenderEvalsSet(Set<SenderEval> senderEvalsSet) {
		this.senderEvalsSet = senderEvalsSet;
	}

	/**
	 * 발송인평가를 추가합니다..
	 * 
	 * @param senderEvals
	 *            발송인평가
	 */
	public void addSenderEvals(SenderEval senderEvals) {
		this.senderEvalsSet.add(senderEvals);
	}

	/**
	 * 발송인평가 목록을 가져옵니다..
	 * 
	 * @return 발송인평가 목록
	 */
	public Set<SenderEval> getSenderEvalsSet() {
		return this.senderEvalsSet;
	}

	/**
	 * EDmoney입출금기록 목록을 설정합니다..
	 * 
	 * @param edmoneyLogsSet
	 *            EDmoney입출금기록 목록
	 */
	public void setEdmoneyLogsSet(Set<EdmoneyLog> edmoneyLogsSet) {
		this.edmoneyLogsSet = edmoneyLogsSet;
	}

	/**
	 * EDmoney입출금기록를 추가합니다..
	 * 
	 * @param edmoneyLogs
	 *            EDmoney입출금기록
	 */
	public void addEdmoneyLogs(EdmoneyLog edmoneyLogs) {
		this.edmoneyLogsSet.add(edmoneyLogs);
	}

	/**
	 * EDmoney입출금기록 목록을 가져옵니다..
	 * 
	 * @return EDmoney입출금기록 목록
	 */
	public Set<EdmoneyLog> getEdmoneyLogsSet() {
		return this.edmoneyLogsSet;
	}

	/**
	 * 의뢰건 목록을 설정합니다..
	 * 
	 * @param requestsSet
	 *            의뢰건 목록
	 */
	public void setRequestsSet(Set<Request> requestsSet) {
		this.requestsSet = requestsSet;
	}

	/**
	 * 의뢰건를 추가합니다..
	 * 
	 * @param requests
	 *            의뢰건
	 */
	public void addRequests(Request requests) {
		this.requestsSet.add(requests);
	}

	/**
	 * 의뢰건 목록을 가져옵니다..
	 * 
	 * @return 의뢰건 목록
	 */
	public Set<Request> getRequestsSet() {
		return this.requestsSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((userId == null) ? 0 : userId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		User other = (User) obj;
		if (userId == null) {
			if (other.userId != null) {
				return false;
			}
		} else if (!userId.equals(other.userId)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "User [userId=" + userId + ", userName=" + userName
				+ ", userPassword=" + userPassword + ", userGender="
				+ userGender + ", userEmail=" + userEmail + ", userBirthdate="
				+ userBirthdate + ", userPhone=" + userPhone + ", userPicture="
				+ userPicture + ", edmoneyBalance=" + edmoneyBalance
				+ ", courierAvgTime=" + courierAvgTime + ", courierAvgKind="
				+ courierAvgKind + ", courierAvgSafe=" + courierAvgSafe
				+ ", courierTotalcnt=" + courierTotalcnt
				+ ", courierSuccesscnt=" + courierSuccesscnt
				+ ", senderAvgTime=" + senderAvgTime + ", senderAvgKind="
				+ senderAvgKind + ", senderAvgThing=" + senderAvgThing
				+ ", senderTotalcnt=" + senderTotalcnt + ", senderSuccesscnt="
				+ senderSuccesscnt + ", alertLogsSet=" + alertLogsSet
				+ ", requestCmtsSet=" + requestCmtsSet + ", courierEvalsSet="
				+ courierEvalsSet + ", senderEvalsSet=" + senderEvalsSet
				+ ", edmoneyLogsSet=" + edmoneyLogsSet + ", requestsSet="
				+ requestsSet + "]";
	}

}
